spring:
    datasource:
        url: jdbc:h2:file:./src/test/resources/testdb/db;IGNORECASE=TRUE
        username: sa
        password: sa
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
            use-new-id-generator-mappings: false

    h2:
        console:
            enabled: true
    sql:
        init:
            mode: embedded
logging:
    level:
        root: DEBUG
        org.springframework.boot.spring-boot-starter-data-rest: DEBUG

